Libhoney client should be initialized as a class variable, not an ivar
honeycombio/rack-honeycomb pull request #5
Opened 2017-12-06 20:11 UTC by christineyen

Or else (especially if they forget to `.close`), the rack integration may look like it never sends events because the client is trashed at the end of each request (before flushing its internal queue of events to send).

2017-12-06 20:58 UTC, samstokes requested changes
Unfortunately, lazy initialisation of class variables is not thread-safe :( The impact is potentially ending up with multiple clients, which is expensive on threads (and therefore memory), and also making it impossible to deterministically .close (though see comment below).

The simplest solution for now is to use a thread-local instead of a class variable: something like `Thread.current[:honeycomb_client] ||= Libhoney::Client.new` (untested).

Once this gem gets closer to prime-time, we can either provide a thread-safe initializer, or encourage clients to do their own initialisation prior to forking of worker threads - unfortunately the details of the latter depend on the web framework and Rack app server being used. (honeycomb-rails doesn't suffer from this problem because we instantiate libhoney in a Rails initializer, which are guaranteed to run once at app startup prior to threads being forked: https://stackoverflow.com/a/34977531.)

Also re "forget to .close" - it's actually pretty hard to .close given the current middleware implementation, even after this fix (you'd have to do something dreadful like `Rack::Honeycomb::Middleware.class_variable_get(:@@honeycomb).close`). We should probably make it easier, or make sure it happens automatically: #6

I'm also :thinking: about the initial problem description:

> Or else (especially if they forget to .close), the rack integration may look like it never sends events because the client is trashed at the end of each request (before flushing its internal queue of events to send).

What makes you think "the client is trashed at the end of each request"? Ruby is garbage collected, so it's possible the `Libhoney::Client` might get cleaned up once the middleware instance holding a reference to it went away, but I wouldn't expect the `TransmissionClient` to be cleaned up given there's a pool of running threads holding references to it. Creating a fresh `Libhoney::Client` per request is still bad, but I'd expect the impact to be leaking threads, not never sending events.

2017-12-06 21:33 UTC, christineyen commented
> What makes you think "the client is trashed at the end of each request"? ... Creating a fresh Libhoney::Client per request is still bad, but I'd expect the impact to be leaking threads, not never sending events.

Yeah, I'd expect that too - but we were seeing zero events getting sent, not the "some set of events" that we started seeing once we went the ^ unthreadsafe route. Will spend some time trying to repro + update this PR (likely with your threadlocal option) to get a reference implementation that actually works in most cases (😢).

(and 💛 for the thorough explanation)

2017-12-06 22:05 UTC, christineyen commented
cc @dankleiman

> unfortunately the details of the latter depend on the web framework and Rack app server being used
In that case, I guess I should stop trying to repro this with some naive little script.

(Speaking of a naive little script, what's the impact of a brute force initialize client + close it in the completion handler? ([for example, with a Faraday middleware wrapper](https://gist.github.com/christineyen/d18ab5b599bbfaa6beaca3ce53014f3d)).)

In any case, this tweaks the `middleware.rb` reference implementation. =\ We should take a pass over our various repos and consider slapping big warnings on repos with code in which we're sufficiently confident.

2017-12-08 14:42 UTC, dankleiman commented
Thanks @christineyen ! Confirming that brute force closing will flush out the messages on each call. We're doing some performance testing on a smaller service, but likely when we fully integrate we'll use the same pattern we use for other analytics messages that come off the application servers -- write to a local file system queue and let a separate process watch the queue + send the messages.

For more context, this was in a rails app, but we set up connections between internal services with a cutout for custom Faraday builders -- that's where I was trying to inject the middleware. Doing the test run with a more railsy connection initialization pattern, then calling close each time in the on_complete block like Christine does in the gist above.

2019-07-23 21:45 UTC, closed without merging